
services:

  victoriametrics:
    image: victoriametrics/victoria-metrics
    container_name: victoriametrics
    restart: unless-stopped
    ports:
      - 0.0.0.0:8428:8428

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 0.0.0.0:3000:3000

  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    environment:
      LOG_LEVEL: info
      VICTORIA_METRICS: http://127.0.0.1:8428
    network_mode: host