
services:

  victoriametrics:
    image: victoriametrics/victoria-metrics
    container_name: victoriametrics
    restart: unless-stopped
    ports:
      - "127.0.0.1:8428:8428"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "0.0.0.0:3000:3000"

  monitor:
    image: ghcr.io/pointnoreturn/monitor:1.0
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      VICTORIA_METRICS: http://127.0.0.1:8428
    restart: unless-stopped
    network_mode: host